version: '3.5'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '5432:5432'
